name: linux

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cxx_compiler: [g++, clang++]
        cc_compiler: [gcc]
        shared: [YES, NO]
        standard: [11, 14, 17, 20]
        build_type: [Debug, Release]

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: dependencies
        run: |
          sudo apt -y update
          sudo apt -y install ninja-build

      - name: Configure
        env:
          CXX: ${{matrix.cxx_compiler}}
          CC: ${{matrix.cc_compiler}}
        run: |
          cmake -S . -B build -D CMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -D CMAKE_CXX_STANDARD=${{matrix.standard}} -G Ninja \
                -D BUILD_SHARED_LIBS=${{matrix.shared}} --preset=ci-coverage

      - name: Build
        run: ninja -C build

      - name: Test
        run: ctest --test-dir build --verbose --output-on-failure --parallel 2
        env:
          CTEST_OUTPUT_ON_FAILURE: True
