name: macos

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        shared: [YES, NO]
        standard: [11, 14, 17, 20]

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -D BUILD_SHARED_LIBS=${{matrix.shared}} \
            -D CMAKE_CXX_STANDARD=${{matrix.standard}} --preset=ci-macos

      - name: Build
        run: cmake --build build  --config ${{matrix.build_type}} --parallel 2

      - name: Test
        run: ctest --test-dir build --verbose --output-on-failure --parallel 2
        env:
          CTEST_OUTPUT_ON_FAILURE: True
